import "@/styles/globals.css";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

import { cn } from "@/lib/utils";
import Providers from "@/app/providers";

export const metadata: Metadata = {
  title: "Mega Issues",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background antialiased font-sans",
          GeistSans.variable,
          GeistMono.variable
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
